language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

install:
  - composer install --prefer-dist --no-dev --optimize-autoloader --quiet

notifications:
  email:
    recipients:
      - peter279k@gmail.com
    on_success: always
    on_failure: always

script: composer test

after_success:
  # Scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
  # CodeCov
  - bash <(curl -s https://codecov.io/bash)
